name: Deploy Flask App to HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          lfs: true  # Ensure LFS files are pulled

      # 2️⃣ Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Install Git LFS
      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install -y git-lfs
          git lfs install

      # 4️⃣ Configure git user for commit
      - name: Configure git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      # 5️⃣ Add, commit changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy latest Flask app" || echo "No changes to commit"

      # 6️⃣ Push to HuggingFace Space using token
      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Store token for non-interactive authentication
          git config credential.helper store
          echo "https://huggingface.co=${HF_TOKEN}" > ~/.git-credentials

          # Push changes
          git push https://huggingface.co/spaces/iamSubha16/imageo main
