name: Build & Deploy Docker to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Compile all Python files to .pyc (hides source code)
      - name: Compile Python files
        run: |
          python -m compileall .

      # 4️⃣ Install Hugging Face CLI
      - name: Install huggingface_hub
        run: pip install huggingface_hub

      # 5️⃣ Log in to Hugging Face using token
      - name: HF Hub Login
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      # 6️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t iamsubha16/imageo:latest .

      # 7️⃣ Push Docker image to Hugging Face Space
      - name: Push Docker image to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          docker tag iamsubha16/imageo:latest ghcr.io/huggingface/spaces/iamsubha16/imageo:latest
          docker login ghcr.io -u iamsubha16 -p $HF_TOKEN
          docker push ghcr.io/huggingface/spaces/iamsubha16/imageo:latest

      # 8️⃣ Notification
      - name: Notify
        run: echo "Docker image successfully pushed to Hugging Face Space!"
