name: Build & Deploy Docker to HF Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (needed for compiling .py files)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Compile all Python files to .pyc (hides source code)
      - name: Compile Python files
        run: |
          python -m compileall .

      # 4️⃣ Log in to Hugging Face Hub container registry
      - name: Login to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | docker login ghcr.io -u iamSubha16 --password-stdin

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/huggingface/spaces/iamSubha16/imageO:latest .

      # 6️⃣ Push Docker image to HF Hub
      - name: Push Docker image
        run: |
          docker push ghcr.io/huggingface/spaces/iamSubha16/imageO:latest

      # 7️⃣ Notify success
      - name: Notify
        run: echo "Docker image pushed to Hugging Face Hub successfully."
