name: Build & Deploy Docker to HF Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your private repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (optional if your Docker build needs Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Login to Hugging Face Hub container registry
      - name: Login to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | docker login --username iamSubha16 --password-stdin huggingface.co

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t imageo:latest .

      # 5️⃣ Tag Docker image for HF Spaces
      - name: Tag Docker image
        run: |
          docker tag imageo:latest huggingface.co/spaces/iamSubha16/imageo:latest

      # 6️⃣ Push Docker image to HF Space
      - name: Push Docker image
        run: |
          docker push huggingface.co/spaces/iamSubha16/imageo:latest

      # 7️⃣ Optional: Notify that image is pushed
      - name: Notification
        run: echo "Docker image pushed to HF Space successfully."
