name: Build & Deploy Docker to HF Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your GitHub repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (optional if your Docker build needs Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Log in to Hugging Face Hub container registry
      - name: Login to HF Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo $HF_TOKEN | docker login ghcr.io -u iamSubha16 --password-stdin

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/iamSubha16/imageO:latest .

      # 5️⃣ Push Docker image to HF Hub
      - name: Push Docker image
        run: |
          docker push ghcr.io/iamSubha16/imageO:latest

      # 6️⃣ Optional: Notify that image is pushed (optional step)
      - name: Notification
        run: echo "Docker image pushed to HF Hub successfully."
