name: Deploy Flask App to Hugging Face Spaces

on:
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your private repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (needed to compile .py files)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      # 3️⃣ Configure git identity for commits
      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # 5️⃣ Clone HF Space repo (without token)
      - name: Clone Hugging Face Space
        run: git clone https://huggingface.co/spaces/iamSubha16/imageO space_repo

      # 6️⃣ Copy all files
      - name: Copy all files
        run: |
          rsync -av --exclude='.git' --exclude='README.md' --exclude='space_repo' ./ ./space_repo/

      # 7️⃣ Commit & Push to HF Space (with token)
      - name: Commit & Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space_repo
          git add .
          git commit -m "Deploy Flask app" || echo "No changes to commit"
          git push https://token:${HF_TOKEN}@huggingface.co/spaces/iamSubha16/imageO main