name: Deploy Flask App to Hugging Face Spaces

on:
  push:
    branches:
      - main  # deploy on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure git identity for commits
      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # 3️⃣ Install Git LFS (for images/binaries)
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      # 4️⃣ Clone HF Space repo
      - name: Clone Hugging Face Space
        run: git clone https://huggingface.co/spaces/iamSubha16/imageO space_repo

      # 5️⃣ Copy all files (except .git) to HF Space repo
      - name: Copy all files
        run: |
          rsync -av --exclude='.git' ./ ./space_repo/

      # 6️⃣ Commit & Push to HF Space
      - name: Commit & Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space_repo
          git add .
          git commit -m "Deploy Flask app" || echo "No changes to commit"
          git push https://token:${HF_TOKEN}@huggingface.co/spaces/iamSubha16/imageO main
