name: Deploy Flask App to HF Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (optional, if you need Python commands in workflow)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3️⃣ Configure git for GitHub Actions bot
      - name: Configure Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      # 4️⃣ Commit changes (if any)
      - name: Commit changes
        run: |
          git add .
          git commit -m "Deploy latest Flask app" || echo "No changes to commit"

      # 5️⃣ Push to HF Space using HF_TOKEN
      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config credential.helper store
          echo "https://huggingface.co:$HF_TOKEN@huggingface.co" > ~/.git-credentials
          git push https://huggingface.co/spaces/iamsubha16/imageo main
