name: Build & Deploy Docker to HF Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your private repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Install Hugging Face Hub CLI
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      # 4️⃣ Login to Hugging Face using CLI
      - name: Login to HF CLI
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t imageo:latest .

      # 6️⃣ Tag Docker image for HF Space
      - name: Tag Docker image
        run: docker tag imageo:latest huggingface.co/spaces/iamsubha16/imageo:latest

      # 7️⃣ Push Docker image to HF Space
      - name: Push Docker image
        run: docker push huggingface.co/spaces/iamsubha16/imageo:latest

      # 8️⃣ Optional: Notify successful push
      - name: Notification
        run: echo "Docker image pushed to Hugging Face Space successfully."
